promoting consistent: don't fail the job if fedora hash is not found
We don't want to skip the entire execution if fedora and centos are not
in sync.
If fedora equivalent is not found, the fedora job will run anyway, but
will test *AND REPORT* on the old tripleo-ci-testing hash, so since the
fedora job is part of the criteria for promotion by default, the hash
will not promote without manual intervention, but we'll get feedback on
the centos jobs.

Change-Id: I5c2df4b146233f102626fdf6d3b62889d434d9f0

diff --git a/playbooks/tripleo-ci-base-promote-consistent-to-tripleo-ci-testing/run.yaml b/playbooks/tripleo-ci-base-promote-consistent-to-tripleo-ci-testing/run.yaml
--- a/playbooks/tripleo-ci-base-promote-consistent-to-tripleo-ci-testing/run.yaml
+++ b/playbooks/tripleo-ci-base-promote-consistent-to-tripleo-ci-testing/run.yaml
@@ -30,36 +30,40 @@
       environment: "{{ zuul | zuul_legacy_vars | combine({'DLRNAPI_PASSWORD': dlrnapi.password}) }}"
 
 
-    - name: Promote consistent to tripleo-ci-testing for fedora repo if an equivalent exists
-      shell:
-        cmd: |
-          export RELEASE="{{ release }}"
-          export PROMOTE_NAME=tripleo-ci-testing
-          DLRNAPI_URL="https://trunk.rdoproject.org/api-fedora-$RELEASE"
-          sed -i -e "s|DLRNAPI_URL=.*|DLRNAPI_URL=$DLRNAPI_URL|" {{ workspace }}/logs/hash_info.sh
+    - block:
+        - name: Promote consistent to tripleo-ci-testing for fedora repo if an equivalent exists
+          shell:
+            cmd: |
+              export RELEASE="{{ release }}"
+              export PROMOTE_NAME=tripleo-ci-testing
+              DLRNAPI_URL="https://trunk.rdoproject.org/api-fedora-$RELEASE"
+              sed -i -e "s|DLRNAPI_URL=.*|DLRNAPI_URL=$DLRNAPI_URL|" {{ workspace }}/logs/hash_info.sh
 
-          source {{ workspace }}/logs/hash_info.sh
-          # Since both fedora and centos repos are created from the same rpm-master branch in distgit
-          # Commit hash and distro hash in both repos will be the same, but theres a catch:
-          # Not all the packages in centos are available in fedora, so we may have a hash in centos
-          # built over a package that doesnt exist in fedora, so the dlrn hash will have no equivalent there.
-          # We test here if the hash exists in fedora, and block the job otherwise.
-          source {{ ci_config_repo }}/ci-scripts/tripleo-upstream/dlrnapi_venv.sh
-          activate_dlrnapi_venv
+              source {{ workspace }}/logs/hash_info.sh
+              # Since both fedora and centos repos are created from the same rpm-master branch in distgit
+              # Commit hash and distro hash in both repos will be the same, but theres a catch:
+              # Not all the packages in centos are available in fedora, so we may have a hash in centos
+              # built over a package that doesnt exist in fedora, so the dlrn hash will have no equivalent there.
+              # We test here if the hash exists in fedora, and block the job otherwise.
+              source {{ ci_config_repo }}/ci-scripts/tripleo-upstream/dlrnapi_venv.sh
+              activate_dlrnapi_venv
 
-          echo "Checking existence of commit $COMMIT_HASH / distro $DISTRO_HASH in fedora"
-          # If the hash combination doesnt exist the API will report 404 and the command will exit 1
-          dlrnapi --url $DLRNAPI_URL repo-status --commit-hash $COMMIT_HASH --distro-hash $DISTRO_HASH > /dev/null
-          if [[ "$?" == "1" ]]; then
-            echo "commit $COMMIT_HASH / distro $DISTRO_HASH combination not found in fedora"
-            exit 1
-          fi
+              echo "Checking existence of commit $COMMIT_HASH / distro $DISTRO_HASH in fedora"
+              # If the hash combination doesnt exist the API will report 404 and the command will exit 1
+              dlrnapi --url $DLRNAPI_URL repo-status --commit-hash $COMMIT_HASH --distro-hash $DISTRO_HASH > /dev/null
+              if [[ "$?" == "1" ]]; then
+                echo "commit $COMMIT_HASH / distro $DISTRO_HASH combination not found in fedora"
+                exit 1
+              fi
 
-          bash -xe {{ ci_config_repo }}/ci-scripts/tripleo-upstream/promote-hash.sh
-        chdir: '{{ workspace }}'
-      environment: "{{ zuul | zuul_legacy_vars | combine({'DLRNAPI_PASSWORD': dlrnapi.password}) }}"
-      when: release == "master"
-      register: result
-      retries: 20
-      delay: 30
-      until: result is succeeded
+              bash -xe {{ ci_config_repo }}/ci-scripts/tripleo-upstream/promote-hash.sh
+            chdir: '{{ workspace }}'
+          environment: "{{ zuul | zuul_legacy_vars | combine({'DLRNAPI_PASSWORD': dlrnapi.password}) }}"
+          when: release == "master"
+          register: result
+          retries: 20
+          delay: 30
+          until: result is succeeded
+      rescue:
+        - debug:
+            msg: "commit $COMMIT_HASH / distro $DISTRO_HASH combination not found in fedora. Fedora mixed job on this run will test *AND REPORT* on the old hash"
