Support register and tag actions for CentOS Stream 10
This change is part of the effort to support CentOS Stream 10.

Partially closes https://issues.redhat.com/browse/RDO-378

Change-Id: Ie26243bb7905b76990943a99a68ad66298a3b041

diff --git a/playbooks/rdoinfo/update-buildsys-tags.yaml b/playbooks/rdoinfo/update-buildsys-tags.yaml
--- a/playbooks/rdoinfo/update-buildsys-tags.yaml
+++ b/playbooks/rdoinfo/update-buildsys-tags.yaml
@@ -120,6 +120,25 @@
                   echo "ERROR: Executing CBS tag actions CentOS Stream 9"
               fi
           fi
+          if [ -s $WORKSPACE/logs/info/register-c10s.yaml ]; then
+              echo "INFO: Executing CBS register actions CentOS Stream 10"
+              cat $WORKSPACE/logs/info/register-c10s.yaml
+              graffiti --centos-release 10s --config-file={{ ansible_user_dir }}/{{ zuul.projects['review.rdoproject.org/gating_scripts'].src_dir }}/buildsys-tags/graffiti_config.yaml --info-file $INFO_FILE register -f $WORKSPACE/logs/info/register-c10s.yaml  # noqa 204
+              if [ $? -ne 0 ]; then
+                  FAILED=1
+                  echo "ERROR: Executing CBS register actions CentOS Stream 10"
+              fi
+          fi
+          # If there are tag actions, they are executed
+          if [ -s $WORKSPACE/logs/info/tags-c10s.yaml ]; then
+              echo "INFO: Executing CBS tag actions CentOS Stream 10"
+              cat $WORKSPACE/logs/info/tags-c10s.yaml
+              graffiti --centos-release 10s --config-file={{ ansible_user_dir }}/{{ zuul.projects['review.rdoproject.org/gating_scripts'].src_dir }}/buildsys-tags/graffiti_config.yaml --info-file $INFO_FILE tag -f $WORKSPACE/logs/info/tags-c10s.yaml  # noqa 204
+              if [ $? -ne 0 ]; then
+                  FAILED=1
+                  echo "ERROR: Executing CBS tag actions CentOS Stream 10"
+              fi
+          fi
           popd
 
           exit $FAILED
