Support graffiti operations for CentOS Stream 8
This is part of the CentOS-Stream-8 implementation [1].

[1] https://review.rdoproject.org/etherpad/p/centos-stream-implementation

Change-Id: Ibf591bac104c5b285a0142c84ccba35fe2c16793
Depends-On: https://softwarefactory-project.io/r/#/c/20709/
Depends-On: https://review.rdoproject.org/r/#/c/31662

diff --git a/playbooks/rdoinfo/update-buildsys-tags.yaml b/playbooks/rdoinfo/update-buildsys-tags.yaml
--- a/playbooks/rdoinfo/update-buildsys-tags.yaml
+++ b/playbooks/rdoinfo/update-buildsys-tags.yaml
@@ -72,6 +72,25 @@
                   echo "ERROR: Executing CBS tag actions CentOS8"
               fi
           fi
+          if [ -s $WORKSPACE/logs/info/register-c8s.yaml ]; then
+              echo "INFO: Executing CBS register actions CentOS Stream 8"
+              cat $WORKSPACE/logs/info/register-c8s.yaml
+              graffiti --centos-release 8s --config-file={{ ansible_user_dir }}/{{ zuul.projects['review.rdoproject.org/gating_scripts'].src_dir }}/buildsys-tags/graffiti_config.yaml register -f $WORKSPACE/logs/info/register-c8s.yaml  # noqa 204
+              if [ $? -ne 0 ]; then
+                  FAILED=1
+                  echo "ERROR: Executing CBS register actions CentOS Stream 8"
+              fi
+          fi
+          # If there are tag actions, they are executed
+          if [ -s $WORKSPACE/logs/info/tags-c8.yaml ]; then
+              echo "INFO: Executing CBS tag actions CentOS Stream 8"
+              cat $WORKSPACE/logs/info/tags-c8s.yaml
+              graffiti --centos-release 8s --config-file={{ ansible_user_dir }}/{{ zuul.projects['review.rdoproject.org/gating_scripts'].src_dir }}/buildsys-tags/graffiti_config.yaml tag -f $WORKSPACE/logs/info/tags-c8s.yaml  # noqa 204
+              if [ $? -ne 0 ]; then
+                  FAILED=1
+                  echo "ERROR: Executing CBS tag actions CentOS Stream 8"
+              fi
+          fi
           popd
 
           exit $FAILED
