Update buildsys-tags job to handle CentOS8 CBS tags
Depends-On: https://review.rdoproject.org/r/#/c/25079/
Change-Id: I1854e3a57339ded0d02e53f57f87f89c023d7a47

diff --git a/playbooks/legacy-update-buildsys-tags/run.yaml b/playbooks/legacy-update-buildsys-tags/run.yaml
--- a/playbooks/legacy-update-buildsys-tags/run.yaml
+++ b/playbooks/legacy-update-buildsys-tags/run.yaml
@@ -82,22 +82,41 @@
           # If there are register actions, they are executed first
           pushd $WORKSPACE/rdoinfo
           if [ -s $WORKSPACE/logs/info/register.yaml ]; then
-              echo "INFO: Executing CBS register actions"
+              echo "INFO: Executing CBS register actions CentOS7"
               cat $WORKSPACE/logs/info/register.yaml
               graffiti --config-file={{ ansible_user_dir }}/{{ zuul.projects['review.rdoproject.org/gating_scripts'].src_dir }}/buildsys-tags/graffiti_config.yaml register -f $WORKSPACE/logs/info/register.yaml  # noqa 204
               if [ $? -ne 0 ]; then
                   FAILED=1
-                  echo "ERROR: Executing CBS register actions"
+                  echo "ERROR: Executing CBS register actions CentOS7"
               fi
           fi
           # If there are tag actions, they are executed
           if [ -s $WORKSPACE/logs/info/tags.yaml ]; then
-              echo "INFO: Executing CBS tag actions"
+              echo "INFO: Executing CBS tag actions CentOS7"
               cat $WORKSPACE/logs/info/tags.yaml
               graffiti --config-file={{ ansible_user_dir }}/{{ zuul.projects['review.rdoproject.org/gating_scripts'].src_dir }}/buildsys-tags/graffiti_config.yaml tag -f $WORKSPACE/logs/info/tags.yaml  # noqa 204
               if [ $? -ne 0 ]; then
                   FAILED=1
-                  echo "ERROR: Executing CBS tag actions"
+                  echo "ERROR: Executing CBS tag actions CentOS7"
+              fi
+          fi
+          if [ -s $WORKSPACE/logs/info/register-c8.yaml ]; then
+              echo "INFO: Executing CBS register actions CentOS8"
+              cat $WORKSPACE/logs/info/register-c8.yaml
+              graffiti --centos-release 8 --config-file={{ ansible_user_dir }}/{{ zuul.projects['review.rdoproject.org/gating_scripts'].src_dir }}/buildsys-tags/graffiti_config.yaml register -f $WORKSPACE/logs/info/register-c8.yaml  # noqa 204
+              if [ $? -ne 0 ]; then
+                  FAILED=1
+                  echo "ERROR: Executing CBS register actions CentOS8"
+              fi
+          fi
+          # If there are tag actions, they are executed
+          if [ -s $WORKSPACE/logs/info/tags-c8.yaml ]; then
+              echo "INFO: Executing CBS tag actions CentOS8"
+              cat $WORKSPACE/logs/info/tags-c8.yaml
+              graffiti --centos-release 8 --config-file={{ ansible_user_dir }}/{{ zuul.projects['review.rdoproject.org/gating_scripts'].src_dir }}/buildsys-tags/graffiti_config.yaml tag -f $WORKSPACE/logs/info/tags-c8.yaml  # noqa 204
+              if [ $? -ne 0 ]; then
+                  FAILED=1
+                  echo "ERROR: Executing CBS tag actions CentOS8"
               fi
           fi
           popd
