Add a check for Jenkins jobs to have an assigned node, take 2
The previous attempt created an issue with the gate because we had
some additional directories in the build/ directory, with files
added by the check script itself. This second attempt fixes that
by using find, looking for files and ignoring files under another
directory.

Change-Id: Id61dc30b8f7c27b2c2b04ee6f6265ae41f2762eb

diff --git a/jobs/_default_jobs.yaml b/jobs/_default_jobs.yaml
--- a/jobs/_default_jobs.yaml
+++ b/jobs/_default_jobs.yaml
@@ -137,6 +137,23 @@
           echo "[+] Checking jobs"
           jenkins-jobs test jobs/ -o ../build/
 
+          echo "[+] Checking all jobs have an assigned node"
+          pushd ../build
+          set +e
+          err=0
+          for file in $(find . -maxdepth 1 -type f) ; do
+            grep assignedNode $file > /dev/null
+            if [ $? -ne 0 ]; then
+              echo "ERROR: Job $file does not have an assigned node"
+              err=1
+            fi
+          done
+          if [ $err -eq 1 ]; then
+             exit 1
+          fi
+          set -e
+          popd
+
           echo "[+] Checking zuul"
           /usr/local/bin/yaml-merger.py zuul | tee ../build/zuul/layout.yaml
           cp zuul/*.py ../build/zuul/ || true
