centos-opstools checks/creates package modified
Currently the creation and the validation of the rpm
packages was based on the name of the project or on a
directory spec/*.spec where any spec file can be.

Everything works perfectly fine when the spec file is
named baseontheproject.spec but it doesn't when the spec
file is under the spec directory due to gating_scripts
jobs.

This aims to fix the rpmbuild and rpmlint jobs so the
spec file can be name baseproject.spec or
any spec file on the root directory.

Change-Id: Ib8f144bff7cfe6cd5ab602bd1300eece95394bc1

diff --git a/jobs/centos-opstools.yaml b/jobs/centos-opstools.yaml
--- a/jobs/centos-opstools.yaml
+++ b/jobs/centos-opstools.yaml
@@ -142,16 +142,14 @@
           if [ -f "$base.spec" ]; then
              specfile="$base.spec"
           else
-            if [ -d spec ]; then
-              specfile=`find spec -depth -maxdepth 1 -name '*.spec' | head -n 1`
+             num_spec=`ls -l *.spec | wc -l`
+             if [ ${num_spec} -eq 1 ]; then
+               specfile=`ls *.spec`
              else
-              echo '*********************************'
-              echo "* There is no $base.spec file    "
-              echo '* There is no spec/anything.spec '
-              echo '*********************************'
+               echo "** ERROR: There are more than one spec file"
+               exit 1
              fi
           fi
-
           rpmlint "$specfile"
           popd
     triggers:
@@ -206,13 +204,12 @@
           if [ -f "$base.spec" ]; then
              specfile="$base.spec"
           else
-             if [ -d spec ]; then
-              specfile=`find spec -depth -maxdepth 1 -name '*.spec' | head -n 1`
+             num_spec=`ls -l *.spec | wc -l`
+             if [ ${num_spec} -eq 1 ]; then
+               specfile=`ls *.spec`
              else
-              echo '*********************************'
-              echo "* There is no $base.spec file    "
-              echo '* There is no spec/anything.spec '
-              echo '*********************************'
+               echo "** ERROR: There are more than one spec file"
+               exit 1
              fi
           fi
           spectool -g  "$specfile"
