Initial job to test upstream openstack/rpm-packaging changes
This job is meant to become a 3rd party CI for the
openstack/rpm-packaging project. Enabling for now so we can start
troubleshooting it.

Change-Id: I24af4707384c4c709b4a5324eeed33b121b81dbd

diff --git a/jobs/DLRN.yaml b/jobs/DLRN.yaml
--- a/jobs/DLRN.yaml
+++ b/jobs/DLRN.yaml
@@ -117,3 +117,87 @@
     triggers:
       - zuul
     node: bare-centos-7
+
+- job:
+    name: 'DLRN-rpmbuild-rpm-packaging'
+    defaults: global
+    builders:
+      - prepare-workspace
+      - prepare-dlrn
+      - shell: |
+          set +e -x
+          pushd DLRN
+          # FIXME(jpena) this is a temp workaround until we get this properly sorted out
+          git fetch http://review.rdoproject.org/r/DLRN refs/changes/59/1559/7 && git cherry-pick FETCH_HEAD
+
+          # Setup virtualenv with tox and use it
+          tox -epy27 --notest
+          . .tox/py27/bin/activate
+          # Prepare config
+          baseurl=http://209.132.178.209/repos/
+          repo="http://github.com/openstack/rpm-packaging"
+          directory="/openstack"
+          skip="openstack-macros"
+          use_version_from_spec="1"
+          pkginfo_driver="dlrn.drivers.gitrepo.GitRepoDriver"
+          branch=${ZUUL_BRANCH}
+
+          # Update the configuration
+          sed -i "s%#repo=.*%repo=${repo}%" projects.ini
+          sed -i "s%#directory=.*%directory=${directory}%" projects.ini
+          sed -i "s%#skip=.*%skip=${skip}%" projects.ini
+          sed -i "s%#use_version_from_spec=.*%use_version_from_spec=${use_version_from_spec}%" projects.ini
+          sed -i "s%pkginfo_driver=.*%pkginfo_driver=${pkginfo_driver}%" projects.ini
+          sed -i "s%baseurl=.*%baseurl=${baseurl}%" projects.ini
+          sed -i "s%source=.*%source=${branch}%" projects.ini
+
+          # Prepare directories
+          mkdir -p data/repos
+
+          if [ -e /usr/bin/zuul-cloner ]; then
+            zuul-cloner --workspace data/ git://git.openstack.org openstack/rpm-packaging --branch ${branch}
+            mv data/openstack/rpm-packaging data/package_info
+          else
+            # We're outside the gate, just do a regular git clone
+            pushd data/
+            # rm -rf first for idempotency
+            rm -rf package_info
+            git clone "git://git.openstack.org/openstack/rpm-packaging" package_info
+            cd package_info
+            git checkout ${branch}
+            popd
+          fi
+
+          # Find out which packages are being tested
+          pushd data/package_info
+          CHANGED_FILES=$(git diff --name-only --diff-filter=ACMT HEAD~1)
+          PACKAGES_TO_BUILD=""
+          for spec in $CHANGED_FILES; do
+            filename=$(echo $spec | awk -F/ '{print $NF}')
+            extension=$(echo $filename | awk -F. '{print $NF}')
+            if [ "$extension" = "j2" ]; then
+                PACKAGES_TO_BUILD="$PACKAGES_TO_BUILD --package-name $(echo $filename | awk -F. '{print $1}')"
+            fi
+          done
+          popd
+          if [ ! -n "${PACKAGES_TO_BUILD}" ]; then
+            exit 0
+          fi
+
+          timeout --signal=SIGKILL 3600 dlrn --config-file projects.ini --head-only $PACKAGES_TO_BUILD --dev --local --verbose-mock
+          ret=$?
+
+          mkdir -p logs
+          rsync -avzr data/repos logs/centos
+          # Clean up mock cache, just in case there is a change for the next run
+          mock -r data/dlrn-1.cfg --scrub=all
+
+          popd
+          mkdir artifacts
+          cp -a DLRN/logs/* artifacts/
+          exit $ret
+    publishers:
+      - zuul-swift-upload
+    triggers:
+      - zuul
+    node: bare-centos-7
