Add new non-voting job to validate fedora rebuilds for deps
As part of the dependencies automation in RDO, a new job in rdoinfo check
pipeline will detects when a change happens in parameter
buildsys-tags: cloud7-openstack-<release>-candidate for a package with
config "fedora-dependency". In this case the job looks for a fedora
build with same nvr (except the dist part) as the specified in the tag
and performs a scratch rebuild in CBS using the srpm from fedora.

For example,  when following change is detected in rdoinfo:

--- a/deps.yml
+++ b/deps.yml
@@ -845,7 +845,7 @@ packages:
   buildsys-tags:
     cloud7-openstack-common-testing: python-django-babel-0.4.0-2.el7
     cloud7-openstack-common-release: python-django-babel-0.4.0-2.el7
     cloud7-openstack-queens-testing: python-django-babel-0.4.0-2.el7
+    cloud7-openstack-queens-candidate: python-django-babel-0.6.2-1.el7

this job will fetch srpm for python-django-babel-0.6.2-1.fc28 from
fedora and will do a scratch cbs build using target
cloud7-openstack-queens-el7.

In this phase the new job is non-voting. Once it's confirmed that it
works as expected it will be moved to voting and a new job to do the
actual build in CBS will be created.

Change-Id: I182569a11ab34e9a448f70d4fee806bafc28a62c

diff --git a/jobs/rdoinfo.yaml b/jobs/rdoinfo.yaml
--- a/jobs/rdoinfo.yaml
+++ b/jobs/rdoinfo.yaml
@@ -40,6 +40,40 @@
           popd
 
 - builder:
+    name: find-fedora-rebuilds
+    builders:
+      - shell: |
+          set -e -x
+          # Install requirements
+          sudo pip install rdopkg
+
+          # Create file to store required rebuilds
+          mkdir -p $WORKSPACE/logs
+          rebuilds_file="$WORKSPACE/logs/fedora_rebuilds.txt"
+          touch $rebuilds_file
+
+          pushd $ZUUL_PROJECT
+          BUILDSYS_TAGS_DIFF=$(rdopkg info-tags-diff -b .)
+          while read line; do
+              pkg_name=$(echo $line |cut -d " " -f 1)
+              tags=$(echo $line |cut -d " " -f 2-| tr -d [],\')
+              for tag in $tags
+              do
+                  PHASE=$(echo $tag|awk -F'-' '{print $4}')
+                  if [ "$PHASE" != "candidate" ]; then
+                      continue
+                  fi
+                  build=$(rdopkg info -l . "name:^${pkg_name}$"| grep "${tag}"|awk '{print $2}')
+                  target=$(echo $tag|sed 's/-candidate/-el7/')
+                  config=$(rdopkg info -l . "name:^${pkg_name}$"| grep "^conf:"|awk '{print $2}')
+                  if [ $config = "fedora-dependency" ]; then
+                      echo "$target $build" | tee -a $rebuilds_file
+                  fi
+              done
+          done <<< "${BUILDSYS_TAGS_DIFF}"
+          popd
+
+- builder:
    name: configure-rdoinfo-oooq-gate-job
    builders:
      - shell:
@@ -350,6 +384,49 @@
         - file:
            credential-id: 4b4632bd-f44b-446d-a8ca-b57eabef0a7c
            variable: LOG_SSH_KEY
+    node: rdo-centos-7
+
+- job:
+    name: validate-fedora-rebuild-deps-nv
+    defaults: rdo-global
+    builders:
+      - rdo-prepare-workspace
+      - rdo-log-setup
+      - find-fedora-rebuilds
+      - prepare-rpmfactory-workspace
+      - shell: |
+          set +e -x
+          sudo yum install -y git centos-packager
+          # clone scripts and run
+          git clone http://review.rdoproject.org/r/gating_scripts
+
+          FAILED=0
+          rebuilds_file="$WORKSPACE/logs/fedora_rebuilds.txt"
+          pushd gating_scripts
+          while read target build
+          do
+              echo "INFO: validating $build on $target"
+              ./validate_rebuild_fedora.sh $target $build
+              if [ $? -ne 0 ];then
+                  echo "ERROR: validation of $build failed on $target"
+                  FAILED=1
+              fi
+          done <<< $(cat $rebuilds_file)
+          popd
+          exit $FAILED
+    publishers:
+      - rdo-rsync-logs
+    triggers:
+      - zuul
+    wrappers:
+      - timestamps
+      - credentials-binding:
+        - file:
+           credential-id: 4b4632bd-f44b-446d-a8ca-b57eabef0a7c
+           variable: LOG_SSH_KEY
+        - file:
+           credential-id: e9b465e2-abfe-418c-8026-edc8c3f21a12
+           variable: CLIENTSECRET
     node: rdo-centos-7
 
 - project:
