Improve error detection in update-buildsys-tags
Tag actions in CBS are not immediate so this patch
is implementing several retries to detect if a tag
action has finished successfully. Additionally, it
implements error checking when running graffiti commands.

Change-Id: Ice7dbfa959ddb0b35084be72a754ce98a004ee07

diff --git a/jobs/rdoinfo.yaml b/jobs/rdoinfo.yaml
--- a/jobs/rdoinfo.yaml
+++ b/jobs/rdoinfo.yaml
@@ -369,6 +369,7 @@
       - prepare-rpmfactory-workspace
       - shell: |
           set +e
+          FAILED=0
           # Install graffiti from hguemar repo until it's moved
           # to some controlled repo
           sudo pip install git+https://github.com/hguemar/graffiti
@@ -379,25 +380,40 @@
               echo "INFO: Executing CBS register actions"
               cat $WORKSPACE/artifacts/info/register.yaml
               graffiti --config-file=$WORKSPACE/gating_scripts/buildsys-tags/graffiti_config.yaml register -f $WORKSPACE/artifacts/info/register.yaml
+              if [ $? -ne 0 ]; then
+                  FAILED=1
+                  echo "ERROR: Executing CBS register actions"
+              fi
           fi
           # If there are tag actions, they are executed
           if [ -s $WORKSPACE/artifacts/info/tags.yaml ]; then
               echo "INFO: Executing CBS tag actions"
               cat $WORKSPACE/artifacts/info/tags.yaml
               graffiti --config-file=$WORKSPACE/gating_scripts/buildsys-tags/graffiti_config.yaml tag -f $WORKSPACE/artifacts/info/tags.yaml
+              if [ $? -ne 0 ]; then
+                  FAILED=1
+                  echo "ERROR: Executing CBS tag actions"
+              fi
           fi
           # Check if tags have been applied as expected
           # format of cbs_actions.txt is <action>,<tag>,<build> where <action> is
           # "tag" for tagging actions.
-          FAILED=0
           for line in $(grep "^tag" $WORKSPACE/artifacts/info/cbs_actions.txt)
           do
               build=$(echo $line|awk -F',' '{print $3'})
               tag=$(echo $line|awk -F',' '{print $2'})
-              TAGGED=$(cbs buildinfo $build|grep -c "Tags.*$tag")
+              i=0
+              TAGGED=0
+              while [ $i -lt 5 -a $TAGGED -eq 0 ]; do
+                  sleep 10
+                  TAGGED=$(cbs buildinfo $build|grep -c "Tags.*$tag")
+                  ((i++))
+              done
               if [ $TAGGED -eq 0 ]; then
                   echo "ERROR: package $build was not included in tag $tag"
                   FAILED=1
+              else
+                  echo "INFO: package $build was added to tag $tag"
               fi
           done
 
