Add new job to rebuild dependencies from fedora in gate
This review:

- Makes voting job rebuild-fedora-dependencies to ensure fedora
  packages can be rebuilt in CBS for new fedora-dependencies
  added to -candidate tags.
- Implement a new job rebuild-fedora-dependencies to do the actual
  rebuild in gate pipeline for updates in -candidate tags.

Depends-On: I36a0ea3a7e887f7e5eab3d7783a4a624ff9cba9a
Change-Id: I5280663afe0ca642d539facaef4a74e405a45753

diff --git a/jobs/rdoinfo.yaml b/jobs/rdoinfo.yaml
--- a/jobs/rdoinfo.yaml
+++ b/jobs/rdoinfo.yaml
@@ -391,7 +391,7 @@
     node: rdo-centos-7
 
 - job:
-    name: validate-dependencies-rebuilds-nv
+    name: validate-dependencies-rebuilds
     defaults: rdo-global
     builders:
       - rdo-prepare-workspace
@@ -461,6 +461,61 @@
            variable: CLIENTSECRET
     node: rdo-centos-7
 
+- job:
+    name: rebuild-fedora-dependencies
+    defaults: rdo-global
+    builders:
+      - rdo-prepare-workspace
+      - rdo-log-setup
+      - find-dependencies-rebuilds
+      - prepare-rpmfactory-workspace
+      - shell: |
+          set +e -x
+          sudo yum install -y git centos-packager
+          # clone scripts and run
+          git clone http://review.rdoproject.org/r/gating_scripts
+
+          FAILED=0
+          fedora_rebuilds_file="$WORKSPACE/logs/fedora_rebuilds.txt"
+          pushd gating_scripts
+          # Rebuilding fedora builds with config fedora-dependency
+          echo "INFO: Rebuilding fedora-dependencies packages"
+          while read target build
+          do
+              if [ -z $target -o -z $build ]; then
+                  continue
+              fi
+              echo "INFO: Checking for $build on CBS"
+              cbs buildinfo $build|grep "No such build"
+              # If build already exist in CBS, don't need to rebuild
+              # it from fedora
+              if [ $? -ne 0 ];then
+                  echo "INFO: build $build exists in CBS"
+                  continue
+              fi
+              echo "INFO: validating $build on $target"
+              ./rebuild_fedora.sh $target $build
+              if [ $? -ne 0 ];then
+                  echo "ERROR: rebuild of $build failed on $target"
+                  FAILED=1
+              fi
+          done <<< $(cat $fedora_rebuilds_file)
+          popd
+          exit $FAILED
+    publishers:
+      - rdo-rsync-logs
+    triggers:
+      - zuul
+    wrappers:
+      - timestamps
+      - credentials-binding:
+        - file:
+           credential-id: 4b4632bd-f44b-446d-a8ca-b57eabef0a7c
+           variable: LOG_SSH_KEY
+        - file:
+           credential-id: e9b465e2-abfe-418c-8026-edc8c3f21a12
+           variable: CLIENTSECRET
+    node: rdo-centos-7
 - project:
     name: rdoinfo-upper-constraints
     branch:
