Update job to handle OS and RDO divergence during new release period
Currently, the rdo-deps-uc-send-review job fetch master branch of
upstream openstack/requirements/upper-constraints.txt file and send
patches against RDO master release branch.
But, during the release period, OpenStack projects branch first and
RDO later on, leading to a divergence. This might introduce wrong
patch proposition by our bot.

Note that the check of the c9s-<new_release>-rdo branch is
already handled in setup_distgit() function [1]

[1] https://review.rdoproject.org/cgit/gating_scripts/tree/rpm-deps-gating-lib.common#n263

Change-Id: I11c735bd613b7a514eb14cdc18c0ad4d1c1c9250
Depends-On: https://softwarefactory-project.io/r/c/rdopkg/+/26376
Closes: https://issues.redhat.com/browse/RDO-55

diff --git a/playbooks/rdo-deps-uc-send-review/run.yaml b/playbooks/rdo-deps-uc-send-review/run.yaml
--- a/playbooks/rdo-deps-uc-send-review/run.yaml
+++ b/playbooks/rdo-deps-uc-send-review/run.yaml
@@ -5,8 +5,22 @@
       shell:
         cmd: |
           set +e -x
-          MASTER_RELEASE="antelope"
+          source '{{ ansible_user_dir }}/rdopkg-venv/bin/activate'
+          MASTER_RELEASE="$(rdopkg info | grep -e "in development phase" | awk '{print $1}')"
+          deactivate
           TOPIC="deps-uc-update"
+
+          UPSTREAM_BRANCHES=$(curl --fail --request GET --url "https://api.github.com/repos/openstack/requirements/branches" --header "Accept: application/vnd.github.v3+json")
+          if [ $? -ne 0 ]; then
+              echo "Error when fetching branches from openstack/requirements repo hosted on GitHub"
+              exit 0
+          fi
+
+          echo -e "$UPSTREAM_BRANCHES" | jq -r '.[].name' | grep -e "stable/$MASTER_RELEASE" >/dev/null 2>&1
+          if [ $? -eq 0 ]; then
+              echo "RDO master release is currently $MASTER_RELEASE, but this release is already in stable branches in https://github.com/openstack/requirements project. Exiting."
+              exit 0
+          fi
 
           GATING_SCRIPTS_BASE="{{ ansible_user_dir }}/{{ zuul.projects['review.rdoproject.org/gating_scripts'].src_dir }}"
           source ${GATING_SCRIPTS_BASE}/deps-uc-send-review.common
