Handle only CS9 dependencies
We clean up the script to only support CS9 deps
auto reviews.

Change-Id: I6be4a420d4dc5ab6cc8c262ef2b5131c45b68db1

diff --git a/playbooks/rdo-deps-uc-send-review/run.yaml b/playbooks/rdo-deps-uc-send-review/run.yaml
--- a/playbooks/rdo-deps-uc-send-review/run.yaml
+++ b/playbooks/rdo-deps-uc-send-review/run.yaml
@@ -15,11 +15,12 @@
 
           BRANCH="{{ zuul.branch }}"
           if [ "$BRANCH" == 'master' ]; then
-              RELEASE="yoga"
+              RELEASE="zed"
           else
-              RELEASE="${BRANCH/stable\//}"
+              echo "INFO: we handle master branch only"
+              exit 0
           fi
-          export PHASE="candidate"
+
           pushd {{ ansible_user_dir }}/{{ zuul.project.src_dir }}
           SUBJECT=$(git log --oneline {{ zuul.newrev }}|head -1|cut -d " " -f 2)
           if [ $SUBJECT == "Merge" ]; then
@@ -31,23 +32,19 @@
           change_list=($(git show $REAL_COMMIT upper-constraints.txt|grep -P '^\+(?:(?!\+\+))|^-(?:(?!--))'))
           change_list=${change_list[@]/#[+-]/}
           popd
+
           if [ -z "${change_list//[[:space:]]/}" ]; then
               echo "INFO: No update in upper-constraints, Exiting"
               exit 0
           fi
+
           GATING_SCRIPTS_BASE="{{ ansible_user_dir }}/{{ zuul.projects['review.rdoproject.org/gating_scripts'].src_dir }}"
-          C7_RELEASES="train"
-          if [ $(echo $C7_RELEASES|grep -c -w $RELEASE) -ne 0 ]; then
-              CENTOS_V=7
-          fi
-          # if not defaults to 9
-          CENTOS_V=${CENTOS_V:-9s}
           pushd {{ ansible_user_dir }}/{{ zuul.projects['review.rdoproject.org/rdoinfo'].src_dir }}
           python ${GATING_SCRIPTS_BASE}/buildsys-tags/add-buildsys-tags.py \
               -l $change_list \
               -r $RELEASE \
-              --centos-release $CENTOS_V \
-              -p $PHASE
+              --centos-release 9s \
+              -p testing
           DIFF=$(git diff *.yml */*.yml)
           popd
 
@@ -66,75 +63,73 @@
           git config --global --add gitreview.username "rdo-trunk"
 
           if [ -n "$DIFF" ]; then
-            NVR=$(echo -e "$DIFF"|grep -P '^\+(?:(?!\+\+))'|grep -e "$RELEASE-$PHASE"|cut -d: -f2|rev|cut -d. -f2-|rev)
-            branch=c$CENTOS_V-$RELEASE-rdo
+            NVR=$(echo -e "$DIFF"|grep -P '^\+(?:(?!\+\+))'|grep -e "$RELEASE-testing"|cut -d: -f2|rev|cut -d. -f2-|rev)
+            branch=c9s-$RELEASE-rdo
             pushd {{ ansible_user_dir }}/{{ zuul.projects['review.rdoproject.org/gating_scripts'].src_dir }}
-            git show
             source ${GATING_SCRIPTS_BASE}/rpm-deps-gating-lib.common
-            if [[ "$CENTOS_V" =~ "9" ]]; then
-              for pkg in $NVR; do
-                needs_update=true
-                change_url=""
-                pkg_name=$(echo $pkg | sed 's/^\(.*\)-\([^-]\{1,\}\)-\([^-]\{1,\}\)$/\1/')
-                pkg_vers=$(echo $pkg | sed 's/^\(.*\)-\([^-]\{1,\}\)-\([^-]\{1,\}\)$/\2/')
-                pkg_nv=$pkg_name-$pkg_vers
-                in_koji_nvr=$(exist_in_koji $pkg_name $pkg_vers koji exact)
-                if [ -z "$in_koji_nvr" ]; then
-                  echo -e "WARNING: there is no build found in Fedora Koji for package $pkg_name"
-                  continue
-                fi
+            for pkg in $NVR; do
+              needs_update=true
+              change_url=""
+              pkg_name=$(echo $pkg | sed 's/^\(.*\)-\([^-]\{1,\}\)-\([^-]\{1,\}\)$/\1/')
+              pkg_vers=$(echo $pkg | sed 's/^\(.*\)-\([^-]\{1,\}\)-\([^-]\{1,\}\)$/\2/')
+              pkg_nv=$pkg_name-$pkg_vers
+              in_koji_nvr=$(exist_in_koji $pkg_name $pkg_vers koji exact)
+              if [ -z "$in_koji_nvr" ]; then
+                echo -e "WARNING: there is no build found in Fedora Koji for package $pkg_name"
+                continue
+              fi
 
-                # We check if there is already an opened change which propose
-                # to update the package to desired $pkg_vers.
-                # If so, we append our commit message with a Depends-On this
-                # change and we ignore sending patch.
-                opened_changes=$(ssh -p 29418 rdo-trunk@review.rdoproject.org \
-                                 gerrit query --format=JSON status:open project:deps/$pkg_name branch:$branch
-                                )
-                opened_change_ids=$(echo "$opened_changes" | jq '.id' | tr -d '"' | sed "s/null//")
-                if [ -n "$opened_change_ids" ]; then
-                  for change_id in $opened_change_ids; do
-                    change_endpoint_url="https://review.rdoproject.org/r/changes/deps%2F$pkg_name~$branch~$change_id/revisions/current"
-                    specfile=$(curl -s -f $change_endpoint_url/files/ | sed 1d | jq 'keys[]' | tr -d '"' | grep -e "\.spec$")
-                    if [ $? -eq 0 ]; then
-                      specfile=$(echo "$specfile" | sed "s/\//%2f/")
-                      curl -s -f $change_endpoint_url/files/$specfile/content | base64 -d | grep -e "^Version:.*$pkg_vers" >/dev/null 2>&1
-                      if [ $? -eq 0 ]; then
-                        needs_update=false
-                        change_url=$(echo "$opened_changes" | jq --arg CHANGE_ID "$change_id" '. | select(.id==$CHANGE_ID) | .url' | tr -d '"')
-                        DEPENDS_ON+="Depends-On: $change_url\n"
-                        continue
-                      fi
-                    fi
-                  done
-                fi
-
-                if $needs_update; then
-                  distgit_status=$(setup_distgit $pkg_name $in_koji_nvr $RELEASE $CENTOS_V)
+              # We check if there is already an opened change which propose
+              # to update the package to desired $pkg_vers.
+              # If so, we append our commit message with a Depends-On this
+              # change and we ignore sending patch.
+              opened_changes=$(ssh -p 29418 rdo-trunk@review.rdoproject.org \
+                               gerrit query --format=JSON status:open project:deps/$pkg_name branch:$branch
+                              )
+              opened_change_ids=$(echo "$opened_changes" | jq '.id' | tr -d '"' | sed "s/null//")
+              if [ -n "$opened_change_ids" ]; then
+                for change_id in $opened_change_ids; do
+                  change_endpoint_url="https://review.rdoproject.org/r/changes/deps%2F$pkg_name~$branch~$change_id/revisions/current"
+                  specfile=$(curl -s -f $change_endpoint_url/files/ | sed 1d | jq 'keys[]' | tr -d '"' | grep -e "\.spec$")
                   if [ $? -eq 0 ]; then
-                    pushd workdir/$pkg_name
-                    git add .
-                    COMMIT_MSG="Update to ${pkg_vers}"
-                    git commit -m "$COMMIT_MSG"
-                    review_status="$(git review c${CENTOS_V}-${RELEASE}-rdo -t cs9-deps-uc-update)"
+                    specfile=$(echo "$specfile" | sed "s/\//%2f/")
+                    curl -s -f $change_endpoint_url/files/$specfile/content | base64 -d | grep -e "^Version:.*$pkg_vers" >/dev/null 2>&1
                     if [ $? -eq 0 ]; then
-                      change_url=$(echo -e "$review_status" | grep -e "$COMMIT_MSG" | awk '{print $2}')
-                      if [ -n $change_url ]; then
-                        DEPENDS_ON+="Depends-On: $change_url\n"
-                      fi
+                      needs_update=false
+                      change_url=$(echo "$opened_changes" | jq --arg CHANGE_ID "$change_id" '. | select(.id==$CHANGE_ID) | .url' | tr -d '"')
+                      DEPENDS_ON+="Depends-On: $change_url\n"
+                      continue
                     fi
-                    popd
-                  else
-                    echo -e "ERROR: while setting up distgit for $pkg_name"
-                    echo -e "$distgit_status"
                   fi
+                done
+              fi
+
+              if $needs_update; then
+                distgit_status=$(setup_distgit $pkg_name $in_koji_nvr $RELEASE 9s)
+                if [ $? -eq 0 ]; then
+                  pushd workdir/$pkg_name
+                  git add .
+                  COMMIT_MSG="Update to ${pkg_vers}"
+                  git commit -m "$COMMIT_MSG"
+                  review_status="$(git review c9s-${RELEASE}-rdo -t cs9-deps-uc-update)"
+                  if [ $? -eq 0 ]; then
+                    change_url=$(echo -e "$review_status" | grep -e "$COMMIT_MSG" | awk '{print $2}')
+                    if [ -n $change_url ]; then
+                      DEPENDS_ON+="Depends-On: $change_url\n"
+                    fi
+                  fi
+                  popd
+                else
+                  echo -e "ERROR: while setting up distgit for $pkg_name"
+                  echo -e "$distgit_status"
                 fi
-              done
-            fi
+              fi
+            done
+
 
             if [ -n "$DEPENDS_ON" ]; then
               pushd {{ ansible_user_dir }}/{{ zuul.projects['review.rdoproject.org/rdoinfo'].src_dir }}
-              COMMIT_MSG="CBS tags sync with uc for $RELEASE-$PHASE\n\nUpstream-Id: $UPSTREAM_CHANGE_ID\n$DEPENDS_ON"
+              COMMIT_MSG="CBS tags sync with uc for $RELEASE-testing\n\nUpstream-Id: $UPSTREAM_CHANGE_ID\n$DEPENDS_ON"
               git checkout -b proposal
               git review -s -v
               echo -e $COMMIT_MSG | git commit -F- *.yml */*.yml
